### ISSUE TITLE
No module named 'mixlib'

### ISSUE THREAD

**Issue by Rhine97** [Qcompiler/MIXQ#1]
### Description
When i wanted to run the basic_quant_quik.py, i got a error with "ModuleNotFoundError: No module named 'mixlib'"

### System Info
```
(llama_env_py39) liyunjie@icrsmp-nodeg:~/MIXQ$ python examples/basic_quant_quik.py --model_path /DIR_LLM/nlp/liyunjie/ocr_model/qwen2-7b-instruct/update_finetune/export_2/checkpoint-1400 --quant_file /DIR_LLM/nlp/liyunjie/ocr_model/qwen2-7b-instruct/update_finetune/quik_quant_int4/checkpoint-1400 --w_bit 4
Traceback (most recent call last):
  File "/home/liyunjie/MIXQ/examples/basic_quant_quik.py", line 9, in <module>
    from mixquant import AutoForCausalLM
  File "/home/liyunjie/MIXQ/mixquant/__init__.py", line 1, in <module>
    from mixquant.models.auto import AutoForCausalLM
  File "/home/liyunjie/MIXQ/mixquant/models/__init__.py", line 1, in <module>
    from .llama import LlamaMixQForCausalLM
  File "/home/liyunjie/MIXQ/mixquant/models/llama.py", line 1, in <module>
    from .base import BaseForCausalLM
  File "/home/liyunjie/MIXQ/mixquant/models/base.py", line 13, in <module>
    from mixquant.modules.linear import   MixLinear_GEMM
  File "/home/liyunjie/MIXQ/mixquant/modules/linear.py", line 9, in <module>
    import mixlib
ModuleNotFoundError: No module named 'mixlib'
```

### Enviroment
python        3.9
autoawq                  0.2.6
autoawq_kernels          0.0.7
torch                    2.3.1
transformers             4.42.0

### question
How could i import this 'mixlib'?

**Comment by Qcompiler** [comment]
Please download the mixlib kernel from https://github.com/Qcompiler/QComplier:

git clone git@github.com:Qcompiler/QComplier.git
cd EETQ 
python setup.py install
cd quantkernel
python setup.py install 

We have updated the readme.md
